import React, { Component } from 'react';
import styles from './Assets/css/styles.min .css';
import SignUp from './SignupButton';
import { socialTwitterOutline } from 'react-icons-kit/ionicons/socialTwitterOutline';
import {iosPaperplaneOutline} from 'react-icons-kit/ionicons/iosPaperplaneOutline';
import Icon from 'react-icons-kit';
import logo from './logo.png';
import Medium from './mediumOutline.png';
import Steem from './Steemit.png';
import Typography from '@material-ui/core/Typography';


class App extends Component {
  constructor(props){
    super(props);
    this.signUp=this.signUp.bind(this);
    this.child = React.createRef();
  }

  signUp(){
    this.child.current.handleClickOpen();
  }

  render() {
    return (
      <div className="App">
        <div className="Page">
          <div className="toplinks">
            <a href="https://t.me/joinchat/EbiqAxL2g2baSz4fulFeHg">
              <div className="telegram">
                <Icon size={40} icon={iosPaperplaneOutline} />
              </div>
            </a>
            <a href="https://twitter.com/Source_platform">
              <div className="twitter">
                <Icon size={30} icon={socialTwitterOutline}/>
              </div>
            </a>
            <a href="https://medium.com/source-blog">
              <div className="medium">
                <img src={Medium} width="30px" alt="medium"/>
              </div>
            </a>
            <a href="https://steemit.com/@sourceplatform">
              <div className="steem">
                <img src={Steem} width="30px" alt="medium"/>
              </div>
            </a>
          </div>
          <div className="all">
            <div className="header">
              <Typography className="Header" variant="caption" style={{marginBottom:"11px"}}>Welcome to</Typography>
              <img src={logo} width="175px" alt="source"/>
            </div>
            <div className="content">
              <p>We’re a group of developers and Open Source enthusiasts disappointed by what’s happening with software collaboration platforms. Most of the value generated by open software is captured by enterprise and rarely reaches the developers that created it.</p>
              <p>We believe that there’s an opportunity to rethink these platforms entirely. By creating a reward distribution system that works, we  can raise project engagement and improve results. Source is an attempt to use blockchain technology to make open source work again.</p>
              <p>Source started as an experiment and has gained ground since. We’re currently testing our alpha, which will be publicly available as a beta soon.  Subscribe to our mailing list if you’d like to hear more, or get in touch with us on telegram.</p>
            </div>
            <div className="subscribe" style={{display:"flex", justifyContent:"center", maxWidth:"355px", width:"90%", marginTop:"30px"}}>
              <SignUp ref={this.child}/>
            </div>
          </div>
        </div>
      </div>
    );
  }
}

export default App;
